export const Colors = {
  background: '#141218',
  surface: '#141218',
  surfaceDim: '#141218',
  surfaceBright: '#3b383e',
  surfaceContainerLowest: '#0f0d13',
  surfaceContainerLow: '#1d1b20',
  surfaceContainer: '#211f24',
  surfaceContainerHigh: '#2b292f',
  surfaceContainerHighest: '#36343a',
  surfaceVariant: '#36343a',
  onSurface: '#e6e0e9',
  onSurfaceVariant: '#cbc4d2',
  inverseSurface: '#e6e0e9',
  inverseOnSurface: '#322f35',
  outline: '#948e9c',
  outlineVariant: '#494551',
  primary: '#cfbcff',
  onPrimary: '#381e72',
  primaryContainer: '#6750a4',
  onPrimaryContainer: '#e0d2ff',
  secondary: '#cdc0e9',
  onSecondary: '#342b4b',
  secondaryContainer: '#4d4465',
  onSecondaryContainer: '#bfb2da',
  tertiary: '#e7c365',
  onTertiary: '#3e2e00',
  tertiaryContainer: '#c9a74d',
  onTertiaryContainer: '#503d00',
  error: '#ffb4ab',
  onError: '#690005',
  errorContainer: '#93000a',
  onErrorContainer: '#ffdad6',
  coral: '#FF6B6B',
  mint: '#4ECDC4',
  seaBlue: '#45B7D1',
  cardBg: '#16213E',
  baseBg: '#1A1A2E',
};

export const Spacing = {
  xs: 4,
  base: 8,
  sm: 12,
  md: 24,
  lg: 40,
  xl: 64,
  safeMargin: 20,
};

export const BorderRadius = {
  sm: 4,
  default: 8,
  md: 12,
  lg: 16,
  xl: 24,
  full: 9999,
};

export const Typography = {
  timerDisplay: {
    fontFamily: 'JetBrainsMono-Bold',
    fontSize: 72,
    lineHeight: 72,
    letterSpacing: -3.6,
  },
  headlineLg: {
    fontFamily: 'PlusJakartaSans-Bold',
    fontSize: 32,
    lineHeight: 40,
  },
  headlineMd: {
    fontFamily: 'PlusJakartaSans-SemiBold',
    fontSize: 24,
    lineHeight: 32,
  },
  bodyLg: {
    fontFamily: 'PlusJakartaSans-Regular',
    fontSize: 18,
    lineHeight: 28,
  },
  bodyMd: {
    fontFamily: 'PlusJakartaSans-Regular',
    fontSize: 16,
    lineHeight: 24,
  },
  labelCaps: {
    fontFamily: 'JetBrainsMono-SemiBold',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 1.2,
    textTransform: 'uppercase' as const,
  },
};
